# Generated by ariadne-codegen
# Source: src/planpilot/providers/github/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class AddSubIssue(BaseModel):
    add_sub_issue: Optional["AddSubIssueAddSubIssue"] = Field(alias="addSubIssue")


class AddSubIssueAddSubIssue(BaseModel):
    issue: Optional["AddSubIssueAddSubIssueIssue"]
    sub_issue: Optional["AddSubIssueAddSubIssueSubIssue"] = Field(alias="subIssue")


class AddSubIssueAddSubIssueIssue(BaseModel):
    id: str


class AddSubIssueAddSubIssueSubIssue(BaseModel):
    id: str


AddSubIssue.model_rebuild()
AddSubIssueAddSubIssue.model_rebuild()
