# Generated by ariadne-codegen
# Source: src/planpilot/providers/github/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class RemoveLabels(BaseModel):
    remove_labels_from_labelable: Optional["RemoveLabelsRemoveLabelsFromLabelable"] = Field(
        alias="removeLabelsFromLabelable"
    )


class RemoveLabelsRemoveLabelsFromLabelable(BaseModel):
    client_mutation_id: Optional[str] = Field(alias="clientMutationId")


RemoveLabels.model_rebuild()
