# Generated by ariadne-codegen
# Source: src/planpilot/providers/github/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import IssueCore


class UpdateIssue(BaseModel):
    update_issue: Optional["UpdateIssueUpdateIssue"] = Field(alias="updateIssue")


class UpdateIssueUpdateIssue(BaseModel):
    issue: Optional["UpdateIssueUpdateIssueIssue"]


class UpdateIssueUpdateIssueIssue(IssueCore):
    pass


UpdateIssue.model_rebuild()
UpdateIssueUpdateIssue.model_rebuild()
