# Generated by ariadne-codegen
# Source: src/planpilot/core/providers/github/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class AddBlockedBy(BaseModel):
    add_blocked_by: Optional["AddBlockedByAddBlockedBy"] = Field(alias="addBlockedBy")


class AddBlockedByAddBlockedBy(BaseModel):
    issue: Optional["AddBlockedByAddBlockedByIssue"]


class AddBlockedByAddBlockedByIssue(BaseModel):
    id: str


AddBlockedBy.model_rebuild()
AddBlockedByAddBlockedBy.model_rebuild()
