# Generated by ariadne-codegen
# Source: src/planpilot/core/providers/github/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class CloseIssue(BaseModel):
    close_issue: Optional["CloseIssueCloseIssue"] = Field(alias="closeIssue")


class CloseIssueCloseIssue(BaseModel):
    issue: Optional["CloseIssueCloseIssueIssue"]


class CloseIssueCloseIssueIssue(BaseModel):
    id: str


CloseIssue.model_rebuild()
CloseIssueCloseIssue.model_rebuild()
