# Generated by ariadne-codegen
# Source: src/planpilot/providers/github/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class CreateLabel(BaseModel):
    create_label: Optional["CreateLabelCreateLabel"] = Field(alias="createLabel")


class CreateLabelCreateLabel(BaseModel):
    label: Optional["CreateLabelCreateLabelLabel"]


class CreateLabelCreateLabelLabel(BaseModel):
    id: str


CreateLabel.model_rebuild()
CreateLabelCreateLabel.model_rebuild()
