# Generated by ariadne-codegen
# Source: src/planpilot/core/providers/github/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import IssueCore


class CreateIssue(BaseModel):
    create_issue: Optional["CreateIssueCreateIssue"] = Field(alias="createIssue")


class CreateIssueCreateIssue(BaseModel):
    issue: Optional["CreateIssueCreateIssueIssue"]


class CreateIssueCreateIssueIssue(IssueCore):
    pass


CreateIssue.model_rebuild()
CreateIssueCreateIssue.model_rebuild()
