# Generated by ariadne-codegen
# Source: src/planpilot/providers/github/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class DeleteIssue(BaseModel):
    delete_issue: Optional["DeleteIssueDeleteIssue"] = Field(alias="deleteIssue")


class DeleteIssueDeleteIssue(BaseModel):
    client_mutation_id: Optional[str] = Field(alias="clientMutationId")


DeleteIssue.model_rebuild()
