# Generated by ariadne-codegen
# Source: src/planpilot/providers/github/operations

from typing import Optional

from .base_model import BaseModel


class FindLabels(BaseModel):
    repository: Optional["FindLabelsRepository"]


class FindLabelsRepository(BaseModel):
    labels: Optional["FindLabelsRepositoryLabels"]


class FindLabelsRepositoryLabels(BaseModel):
    nodes: Optional[list[Optional["FindLabelsRepositoryLabelsNodes"]]]


class FindLabelsRepositoryLabelsNodes(BaseModel):
    id: str
    name: str


FindLabels.model_rebuild()
FindLabelsRepository.model_rebuild()
FindLabelsRepositoryLabels.model_rebuild()
