# Generated by ariadne-codegen
# Source: src/planpilot/providers/github/operations

__all__ = [
    "ADD_BLOCKED_BY_GQL",
    "ADD_LABELS_GQL",
    "ADD_PROJECT_ITEM_GQL",
    "ADD_SUB_ISSUE_GQL",
    "CLOSE_ISSUE_GQL",
    "CREATE_ISSUE_GQL",
    "CREATE_LABEL_GQL",
    "DELETE_ISSUE_GQL",
    "FETCH_ORG_PROJECT_GQL",
    "FETCH_PROJECT_FIELDS_GQL",
    "FETCH_PROJECT_ITEMS_GQL",
    "FETCH_RELATIONS_GQL",
    "FETCH_REPO_GQL",
    "FETCH_USER_PROJECT_GQL",
    "FIND_LABELS_GQL",
    "GET_ISSUE_GQL",
    "REMOVE_BLOCKED_BY_GQL",
    "REMOVE_LABELS_GQL",
    "REMOVE_SUB_ISSUE_GQL",
    "SEARCH_ISSUES_GQL",
    "UPDATE_ISSUE_GQL",
    "UPDATE_PROJECT_FIELD_GQL",
]

ADD_BLOCKED_BY_GQL = """
mutation AddBlockedBy($blockedId: ID!, $blockerId: ID!) {
  addBlockedBy(input: {issueId: $blockedId, blockingIssueId: $blockerId}) {
    issue {
      id
    }
  }
}
"""

ADD_LABELS_GQL = """
mutation AddLabels($labelableId: ID!, $labelIds: [ID!]!) {
  addLabelsToLabelable(input: {labelableId: $labelableId, labelIds: $labelIds}) {
    clientMutationId
  }
}
"""

ADD_PROJECT_ITEM_GQL = """
mutation AddProjectItem($projectId: ID!, $contentId: ID!) {
  addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
    item {
      id
    }
  }
}
"""

ADD_SUB_ISSUE_GQL = """
mutation AddSubIssue($parentId: ID!, $childId: ID!, $replaceParent: Boolean) {
  addSubIssue(
    input: {issueId: $parentId, subIssueId: $childId, replaceParent: $replaceParent}
  ) {
    issue {
      id
    }
    subIssue {
      id
    }
  }
}
"""

CLOSE_ISSUE_GQL = """
mutation CloseIssue($issueId: ID!, $stateReason: IssueClosedStateReason) {
  closeIssue(input: {issueId: $issueId, stateReason: $stateReason}) {
    issue {
      id
    }
  }
}
"""

CREATE_ISSUE_GQL = """
mutation CreateIssue($repositoryId: ID!, $title: String!, $body: String!, $labelIds: [ID!], $issueTypeId: ID, $projectV2Ids: [ID!], $parentIssueId: ID) {
  createIssue(
    input: {repositoryId: $repositoryId, title: $title, body: $body, labelIds: $labelIds, issueTypeId: $issueTypeId, projectV2Ids: $projectV2Ids, parentIssueId: $parentIssueId}
  ) {
    issue {
      ...IssueCore
    }
  }
}

fragment IssueCore on Issue {
  id
  number
  url
  title
  body
  labels(first: 100) {
    nodes {
      id
      name
    }
  }
}
"""

CREATE_LABEL_GQL = """
mutation CreateLabel($repositoryId: ID!, $name: String!) {
  createLabel(input: {repositoryId: $repositoryId, name: $name, color: "0366d6"}) {
    label {
      id
    }
  }
}
"""

DELETE_ISSUE_GQL = """
mutation DeleteIssue($issueId: ID!) {
  deleteIssue(input: {issueId: $issueId}) {
    clientMutationId
  }
}
"""

FETCH_ORG_PROJECT_GQL = """
query FetchOrgProject($owner: String!, $number: Int!) {
  organization(login: $owner) {
    projectV2(number: $number) {
      id
    }
  }
}
"""

FETCH_PROJECT_FIELDS_GQL = """
query FetchProjectFields($projectId: ID!) {
  node(id: $projectId) {
    __typename
    ... on ProjectV2 {
      fields(first: 50) {
        nodes {
          __typename
          ... on ProjectV2Field {
            id
            name
            dataType
          }
          ... on ProjectV2SingleSelectField {
            id
            name
            dataType
            options {
              id
              name
            }
          }
          ... on ProjectV2IterationField {
            id
            name
            dataType
            configuration {
              iterations {
                id
                title
                startDate
                duration
              }
            }
          }
        }
      }
    }
  }
}
"""

FETCH_PROJECT_ITEMS_GQL = """
query FetchProjectItems($projectId: ID!, $cursor: String) {
  node(id: $projectId) {
    __typename
    ... on ProjectV2 {
      items(first: 100, after: $cursor) {
        pageInfo {
          hasNextPage
          endCursor
        }
        nodes {
          id
          content {
            __typename
            ... on Issue {
              id
            }
          }
        }
      }
    }
  }
}
"""

FETCH_RELATIONS_GQL = """
query FetchRelations($ids: [ID!]!) {
  nodes(ids: $ids) {
    __typename
    ... on Issue {
      id
      parent {
        id
      }
      blockedBy(first: 100) {
        nodes {
          id
        }
      }
    }
  }
}
"""

FETCH_REPO_GQL = """
query FetchRepo($owner: String!, $name: String!) {
  repository(owner: $owner, name: $name) {
    id
    labels(first: 100) {
      nodes {
        id
        name
      }
    }
    issueTypes(first: 100) {
      nodes {
        id
        name
      }
    }
  }
}
"""

FETCH_USER_PROJECT_GQL = """
query FetchUserProject($owner: String!, $number: Int!) {
  user(login: $owner) {
    projectV2(number: $number) {
      id
    }
  }
}
"""

FIND_LABELS_GQL = """
query FindLabels($owner: String!, $name: String!, $query: String!) {
  repository(owner: $owner, name: $name) {
    labels(first: 100, query: $query) {
      nodes {
        id
        name
      }
    }
  }
}
"""

GET_ISSUE_GQL = """
query GetIssue($id: ID!) {
  node(id: $id) {
    __typename
    ... on Issue {
      ...IssueCore
    }
  }
}

fragment IssueCore on Issue {
  id
  number
  url
  title
  body
  labels(first: 100) {
    nodes {
      id
      name
    }
  }
}
"""

REMOVE_BLOCKED_BY_GQL = """
mutation RemoveBlockedBy($blockedId: ID!, $blockerId: ID!) {
  removeBlockedBy(input: {issueId: $blockedId, blockingIssueId: $blockerId}) {
    issue {
      id
    }
  }
}
"""

REMOVE_LABELS_GQL = """
mutation RemoveLabels($labelableId: ID!, $labelIds: [ID!]!) {
  removeLabelsFromLabelable(
    input: {labelableId: $labelableId, labelIds: $labelIds}
  ) {
    clientMutationId
  }
}
"""

REMOVE_SUB_ISSUE_GQL = """
mutation RemoveSubIssue($parentId: ID!, $childId: ID!) {
  removeSubIssue(input: {issueId: $parentId, subIssueId: $childId}) {
    issue {
      id
    }
    subIssue {
      id
    }
  }
}
"""

SEARCH_ISSUES_GQL = """
query SearchIssues($query: String!, $cursor: String) {
  search(type: ISSUE, query: $query, first: 100, after: $cursor) {
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      __typename
      ... on Issue {
        ...IssueCore
      }
    }
  }
}

fragment IssueCore on Issue {
  id
  number
  url
  title
  body
  labels(first: 100) {
    nodes {
      id
      name
    }
  }
}
"""

UPDATE_ISSUE_GQL = """
mutation UpdateIssue($id: ID!, $title: String, $body: String, $issueTypeId: ID, $labelIds: [ID!]) {
  updateIssue(
    input: {id: $id, title: $title, body: $body, issueTypeId: $issueTypeId, labelIds: $labelIds}
  ) {
    issue {
      ...IssueCore
    }
  }
}

fragment IssueCore on Issue {
  id
  number
  url
  title
  body
  labels(first: 100) {
    nodes {
      id
      name
    }
  }
}
"""

UPDATE_PROJECT_FIELD_GQL = """
mutation UpdateProjectField($projectId: ID!, $itemId: ID!, $fieldId: ID!, $optionId: String!) {
  updateProjectV2ItemFieldValue(
    input: {projectId: $projectId, itemId: $itemId, fieldId: $fieldId, value: {singleSelectOptionId: $optionId}}
  ) {
    projectV2Item {
      id
    }
  }
}
"""
