# Generated by ariadne-codegen
# Source: src/planpilot/core/providers/github/operations

from typing import Annotated, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .fragments import IssueCore


class SearchIssues(BaseModel):
    search: "SearchIssuesSearch"


class SearchIssuesSearch(BaseModel):
    page_info: "SearchIssuesSearchPageInfo" = Field(alias="pageInfo")
    nodes: Optional[
        list[
            Optional[
                Annotated[
                    Union[
                        "SearchIssuesSearchNodesApp",
                        "SearchIssuesSearchNodesDiscussion",
                        "SearchIssuesSearchNodesIssue",
                        "SearchIssuesSearchNodesMarketplaceListing",
                        "SearchIssuesSearchNodesOrganization",
                        "SearchIssuesSearchNodesPullRequest",
                        "SearchIssuesSearchNodesRepository",
                        "SearchIssuesSearchNodesUser",
                    ],
                    Field(discriminator="typename__"),
                ]
            ]
        ]
    ]


class SearchIssuesSearchPageInfo(BaseModel):
    has_next_page: bool = Field(alias="hasNextPage")
    end_cursor: Optional[str] = Field(alias="endCursor")


class SearchIssuesSearchNodesApp(BaseModel):
    typename__: Literal["App"] = Field(alias="__typename")


class SearchIssuesSearchNodesDiscussion(BaseModel):
    typename__: Literal["Discussion"] = Field(alias="__typename")


class SearchIssuesSearchNodesIssue(IssueCore):
    typename__: Literal["Issue"] = Field(alias="__typename")


class SearchIssuesSearchNodesMarketplaceListing(BaseModel):
    typename__: Literal["MarketplaceListing"] = Field(alias="__typename")


class SearchIssuesSearchNodesOrganization(BaseModel):
    typename__: Literal["Organization"] = Field(alias="__typename")


class SearchIssuesSearchNodesPullRequest(BaseModel):
    typename__: Literal["PullRequest"] = Field(alias="__typename")


class SearchIssuesSearchNodesRepository(BaseModel):
    typename__: Literal["Repository"] = Field(alias="__typename")


class SearchIssuesSearchNodesUser(BaseModel):
    typename__: Literal["User"] = Field(alias="__typename")


SearchIssues.model_rebuild()
SearchIssuesSearch.model_rebuild()
