# Generated by ariadne-codegen
# Source: src/planpilot_v2/providers/github/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class AddProjectItem(BaseModel):
    add_project_v_2_item_by_id: Optional["AddProjectItemAddProjectV2ItemById"] = Field(
        alias="addProjectV2ItemById"
    )


class AddProjectItemAddProjectV2ItemById(BaseModel):
    item: Optional["AddProjectItemAddProjectV2ItemByIdItem"]


class AddProjectItemAddProjectV2ItemByIdItem(BaseModel):
    id: str


AddProjectItem.model_rebuild()
AddProjectItemAddProjectV2ItemById.model_rebuild()
