# Generated by ariadne-codegen
# Source: src/planpilot_v2/providers/github/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class AddSubIssue(BaseModel):
    add_sub_issue: Optional["AddSubIssueAddSubIssue"] = Field(alias="addSubIssue")


class AddSubIssueAddSubIssue(BaseModel):
    issue: Optional["AddSubIssueAddSubIssueIssue"]


class AddSubIssueAddSubIssueIssue(BaseModel):
    id: str


AddSubIssue.model_rebuild()
AddSubIssueAddSubIssue.model_rebuild()
