# Generated by ariadne-codegen
# Source: src/planpilot_v2/providers/github/operations

from typing import TYPE_CHECKING, Any, Union

from .async_base_client import AsyncBaseClient
from .base_model import UNSET
from .operations import (
    ADD_BLOCKED_BY_GQL,
    ADD_PROJECT_ITEM_GQL,
    ADD_SUB_ISSUE_GQL,
    CREATE_ISSUE_GQL,
    CREATE_LABEL_GQL,
    FETCH_PROJECT_GQL,
    FETCH_PROJECT_ITEMS_GQL,
    FETCH_RELATIONS_GQL,
    FETCH_REPO_GQL,
    SEARCH_ISSUES_GQL,
    UPDATE_ISSUE_GQL,
    UPDATE_PROJECT_FIELD_GQL,
)

if TYPE_CHECKING:
    from .add_blocked_by import AddBlockedBy
    from .add_project_item import AddProjectItem
    from .add_sub_issue import AddSubIssue
    from .base_model import UnsetType
    from .create_issue import CreateIssue
    from .create_label import CreateLabel
    from .fetch_project import FetchProject
    from .fetch_project_items import FetchProjectItems
    from .fetch_relations import FetchRelations
    from .fetch_repo import FetchRepo
    from .search_issues import SearchIssues
    from .update_issue import UpdateIssue
    from .update_project_field import UpdateProjectField


def gql(q: str) -> str:
    return q


class GitHubGraphQLClient(AsyncBaseClient):
    async def add_blocked_by(self, blocked_id: str, blocker_id: str, **kwargs: Any) -> "AddBlockedBy":
        from .add_blocked_by import AddBlockedBy

        variables: dict[str, object] = {
            "blockedId": blocked_id,
            "blockerId": blocker_id,
        }
        response = await self.execute(
            query=ADD_BLOCKED_BY_GQL, operation_name="AddBlockedBy", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return AddBlockedBy.model_validate(data)

    async def add_project_item(self, project_id: str, content_id: str, **kwargs: Any) -> "AddProjectItem":
        from .add_project_item import AddProjectItem

        variables: dict[str, object] = {
            "projectId": project_id,
            "contentId": content_id,
        }
        response = await self.execute(
            query=ADD_PROJECT_ITEM_GQL, operation_name="AddProjectItem", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return AddProjectItem.model_validate(data)

    async def add_sub_issue(self, parent_id: str, child_id: str, **kwargs: Any) -> "AddSubIssue":
        from .add_sub_issue import AddSubIssue

        variables: dict[str, object] = {"parentId": parent_id, "childId": child_id}
        response = await self.execute(
            query=ADD_SUB_ISSUE_GQL, operation_name="AddSubIssue", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return AddSubIssue.model_validate(data)

    async def create_issue(self, repository_id: str, title: str, body: str, **kwargs: Any) -> "CreateIssue":
        from .create_issue import CreateIssue

        variables: dict[str, object] = {
            "repositoryId": repository_id,
            "title": title,
            "body": body,
        }
        response = await self.execute(
            query=CREATE_ISSUE_GQL, operation_name="CreateIssue", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CreateIssue.model_validate(data)

    async def create_label(self, repository_id: str, name: str, **kwargs: Any) -> "CreateLabel":
        from .create_label import CreateLabel

        variables: dict[str, object] = {"repositoryId": repository_id, "name": name}
        response = await self.execute(
            query=CREATE_LABEL_GQL, operation_name="CreateLabel", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CreateLabel.model_validate(data)

    async def fetch_project(self, owner: str, number: int, **kwargs: Any) -> "FetchProject":
        from .fetch_project import FetchProject

        variables: dict[str, object] = {"owner": owner, "number": number}
        response = await self.execute(
            query=FETCH_PROJECT_GQL, operation_name="FetchProject", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return FetchProject.model_validate(data)

    async def fetch_project_items(
        self, project_id: str, cursor: Union[str | None, "UnsetType"] = UNSET, **kwargs: Any
    ) -> "FetchProjectItems":
        from .fetch_project_items import FetchProjectItems

        variables: dict[str, object] = {"projectId": project_id, "cursor": cursor}
        response = await self.execute(
            query=FETCH_PROJECT_ITEMS_GQL, operation_name="FetchProjectItems", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return FetchProjectItems.model_validate(data)

    async def fetch_relations(self, ids: list[str], **kwargs: Any) -> "FetchRelations":
        from .fetch_relations import FetchRelations

        variables: dict[str, object] = {"ids": ids}
        response = await self.execute(
            query=FETCH_RELATIONS_GQL, operation_name="FetchRelations", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return FetchRelations.model_validate(data)

    async def fetch_repo(self, owner: str, name: str, **kwargs: Any) -> "FetchRepo":
        from .fetch_repo import FetchRepo

        variables: dict[str, object] = {"owner": owner, "name": name}
        response = await self.execute(query=FETCH_REPO_GQL, operation_name="FetchRepo", variables=variables, **kwargs)
        data = self.get_data(response)
        return FetchRepo.model_validate(data)

    async def search_issues(
        self, query: str, cursor: Union[str | None, "UnsetType"] = UNSET, **kwargs: Any
    ) -> "SearchIssues":
        from .search_issues import SearchIssues

        variables: dict[str, object] = {"query": query, "cursor": cursor}
        response = await self.execute(
            query=SEARCH_ISSUES_GQL, operation_name="SearchIssues", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return SearchIssues.model_validate(data)

    async def update_issue(
        self,
        id: str,
        title: Union[str | None, "UnsetType"] = UNSET,
        body: Union[str | None, "UnsetType"] = UNSET,
        **kwargs: Any,
    ) -> "UpdateIssue":
        from .update_issue import UpdateIssue

        variables: dict[str, object] = {"id": id, "title": title, "body": body}
        response = await self.execute(
            query=UPDATE_ISSUE_GQL, operation_name="UpdateIssue", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return UpdateIssue.model_validate(data)

    async def update_project_field(
        self, project_id: str, item_id: str, field_id: str, option_id: str, **kwargs: Any
    ) -> "UpdateProjectField":
        from .update_project_field import UpdateProjectField

        variables: dict[str, object] = {
            "projectId": project_id,
            "itemId": item_id,
            "fieldId": field_id,
            "optionId": option_id,
        }
        response = await self.execute(
            query=UPDATE_PROJECT_FIELD_GQL, operation_name="UpdateProjectField", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return UpdateProjectField.model_validate(data)
