# Generated by ariadne-codegen
# Source: src/planpilot_v2/providers/github/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class CreateIssue(BaseModel):
    create_issue: Optional["CreateIssueCreateIssue"] = Field(alias="createIssue")


class CreateIssueCreateIssue(BaseModel):
    issue: Optional["CreateIssueCreateIssueIssue"]


class CreateIssueCreateIssueIssue(BaseModel):
    id: str


CreateIssue.model_rebuild()
CreateIssueCreateIssue.model_rebuild()
