# Generated by ariadne-codegen
# Source: src/planpilot_v2/providers/github/schema.graphql

from enum import Enum


class IssueClosedStateReason(str, Enum):
    COMPLETED = "COMPLETED"
    NOT_PLANNED = "NOT_PLANNED"
    DUPLICATE = "DUPLICATE"


class ProjectV2FieldType(str, Enum):
    ASSIGNEES = "ASSIGNEES"
    LINKED_PULL_REQUESTS = "LINKED_PULL_REQUESTS"
    REVIEWERS = "REVIEWERS"
    LABELS = "LABELS"
    MILESTONE = "MILESTONE"
    REPOSITORY = "REPOSITORY"
    TITLE = "TITLE"
    TEXT = "TEXT"
    SINGLE_SELECT = "SINGLE_SELECT"
    NUMBER = "NUMBER"
    DATE = "DATE"
    ITERATION = "ITERATION"
    TRACKS = "TRACKS"
    TRACKED_BY = "TRACKED_BY"
    ISSUE_TYPE = "ISSUE_TYPE"
    PARENT_ISSUE = "PARENT_ISSUE"
    SUB_ISSUES_PROGRESS = "SUB_ISSUES_PROGRESS"
