# Generated by ariadne-codegen
# Source: src/planpilot_v2/providers/github/operations

from datetime import date
from typing import Annotated, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import ProjectV2FieldType


class FetchProjectFields(BaseModel):
    node: Optional[
        Annotated[
            Union["FetchProjectFieldsNodeNode", "FetchProjectFieldsNodeProjectV2"],
            Field(discriminator="typename__"),
        ]
    ]


class FetchProjectFieldsNodeNode(BaseModel):
    typename__: Literal[
        "AddedToMergeQueueEvent",
        "AddedToProjectEvent",
        "AddedToProjectV2Event",
        "App",
        "AssignedEvent",
        "AutoMergeDisabledEvent",
        "AutoMergeEnabledEvent",
        "AutoRebaseEnabledEvent",
        "AutoSquashEnabledEvent",
        "AutomaticBaseChangeFailedEvent",
        "AutomaticBaseChangeSucceededEvent",
        "BaseRefChangedEvent",
        "BaseRefDeletedEvent",
        "BaseRefForcePushedEvent",
        "Blob",
        "BlockedByAddedEvent",
        "BlockedByRemovedEvent",
        "BlockingAddedEvent",
        "BlockingRemovedEvent",
        "Bot",
        "BranchProtectionRule",
        "BypassForcePushAllowance",
        "BypassPullRequestAllowance",
        "CWE",
        "CheckRun",
        "CheckSuite",
        "ClosedEvent",
        "CodeOfConduct",
        "CommentDeletedEvent",
        "Commit",
        "CommitComment",
        "CommitCommentThread",
        "Comparison",
        "ConnectedEvent",
        "ConvertToDraftEvent",
        "ConvertedFromDraftEvent",
        "ConvertedNoteToIssueEvent",
        "ConvertedToDiscussionEvent",
        "CrossReferencedEvent",
        "DemilestonedEvent",
        "DependencyGraphManifest",
        "DeployKey",
        "DeployedEvent",
        "Deployment",
        "DeploymentEnvironmentChangedEvent",
        "DeploymentReview",
        "DeploymentStatus",
        "DisconnectedEvent",
        "Discussion",
        "DiscussionCategory",
        "DiscussionComment",
        "DiscussionPoll",
        "DiscussionPollOption",
        "DraftIssue",
        "Enterprise",
        "EnterpriseAdministratorInvitation",
        "EnterpriseIdentityProvider",
        "EnterpriseMemberInvitation",
        "EnterpriseRepositoryInfo",
        "EnterpriseServerInstallation",
        "EnterpriseServerUserAccount",
        "EnterpriseServerUserAccountEmail",
        "EnterpriseServerUserAccountsUpload",
        "EnterpriseUserAccount",
        "Environment",
        "ExternalIdentity",
        "Gist",
        "GistComment",
        "HeadRefDeletedEvent",
        "HeadRefForcePushedEvent",
        "HeadRefRestoredEvent",
        "IpAllowListEntry",
        "Issue",
        "IssueComment",
        "IssueType",
        "IssueTypeAddedEvent",
        "IssueTypeChangedEvent",
        "IssueTypeRemovedEvent",
        "Label",
        "LabeledEvent",
        "Language",
        "License",
        "LinkedBranch",
        "LockedEvent",
        "Mannequin",
        "MarkedAsDuplicateEvent",
        "MarketplaceCategory",
        "MarketplaceListing",
        "MemberFeatureRequestNotification",
        "MembersCanDeleteReposClearAuditEntry",
        "MembersCanDeleteReposDisableAuditEntry",
        "MembersCanDeleteReposEnableAuditEntry",
        "MentionedEvent",
        "MergeQueue",
        "MergeQueueEntry",
        "MergedEvent",
        "MigrationSource",
        "Milestone",
        "MilestonedEvent",
        "MovedColumnsInProjectEvent",
        "Node",
        "NotificationThread",
        "OIDCProvider",
        "OauthApplicationCreateAuditEntry",
        "OrgAddBillingManagerAuditEntry",
        "OrgAddMemberAuditEntry",
        "OrgBlockUserAuditEntry",
        "OrgConfigDisableCollaboratorsOnlyAuditEntry",
        "OrgConfigEnableCollaboratorsOnlyAuditEntry",
        "OrgCreateAuditEntry",
        "OrgDisableOauthAppRestrictionsAuditEntry",
        "OrgDisableSamlAuditEntry",
        "OrgDisableTwoFactorRequirementAuditEntry",
        "OrgEnableOauthAppRestrictionsAuditEntry",
        "OrgEnableSamlAuditEntry",
        "OrgEnableTwoFactorRequirementAuditEntry",
        "OrgInviteMemberAuditEntry",
        "OrgInviteToBusinessAuditEntry",
        "OrgOauthAppAccessApprovedAuditEntry",
        "OrgOauthAppAccessBlockedAuditEntry",
        "OrgOauthAppAccessDeniedAuditEntry",
        "OrgOauthAppAccessRequestedAuditEntry",
        "OrgOauthAppAccessUnblockedAuditEntry",
        "OrgRemoveBillingManagerAuditEntry",
        "OrgRemoveMemberAuditEntry",
        "OrgRemoveOutsideCollaboratorAuditEntry",
        "OrgRestoreMemberAuditEntry",
        "OrgUnblockUserAuditEntry",
        "OrgUpdateDefaultRepositoryPermissionAuditEntry",
        "OrgUpdateMemberAuditEntry",
        "OrgUpdateMemberRepositoryCreationPermissionAuditEntry",
        "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry",
        "Organization",
        "OrganizationIdentityProvider",
        "OrganizationInvitation",
        "OrganizationMigration",
        "Package",
        "PackageFile",
        "PackageTag",
        "PackageVersion",
        "ParentIssueAddedEvent",
        "ParentIssueRemovedEvent",
        "PinnedDiscussion",
        "PinnedEnvironment",
        "PinnedEvent",
        "PinnedIssue",
        "PrivateRepositoryForkingDisableAuditEntry",
        "PrivateRepositoryForkingEnableAuditEntry",
        "Project",
        "ProjectCard",
        "ProjectColumn",
        "ProjectV2Field",
        "ProjectV2Item",
        "ProjectV2ItemFieldDateValue",
        "ProjectV2ItemFieldIterationValue",
        "ProjectV2ItemFieldNumberValue",
        "ProjectV2ItemFieldSingleSelectValue",
        "ProjectV2ItemFieldTextValue",
        "ProjectV2ItemStatusChangedEvent",
        "ProjectV2IterationField",
        "ProjectV2SingleSelectField",
        "ProjectV2StatusUpdate",
        "ProjectV2View",
        "ProjectV2Workflow",
        "PublicKey",
        "PullRequest",
        "PullRequestCommit",
        "PullRequestCommitCommentThread",
        "PullRequestReview",
        "PullRequestReviewComment",
        "PullRequestReviewThread",
        "PullRequestThread",
        "Push",
        "PushAllowance",
        "Query",
        "Reaction",
        "ReadyForReviewEvent",
        "Ref",
        "ReferencedEvent",
        "Release",
        "ReleaseAsset",
        "RemovedFromMergeQueueEvent",
        "RemovedFromProjectEvent",
        "RemovedFromProjectV2Event",
        "RenamedTitleEvent",
        "ReopenedEvent",
        "RepoAccessAuditEntry",
        "RepoAddMemberAuditEntry",
        "RepoAddTopicAuditEntry",
        "RepoArchivedAuditEntry",
        "RepoChangeMergeSettingAuditEntry",
        "RepoConfigDisableAnonymousGitAccessAuditEntry",
        "RepoConfigDisableCollaboratorsOnlyAuditEntry",
        "RepoConfigDisableContributorsOnlyAuditEntry",
        "RepoConfigDisableSockpuppetDisallowedAuditEntry",
        "RepoConfigEnableAnonymousGitAccessAuditEntry",
        "RepoConfigEnableCollaboratorsOnlyAuditEntry",
        "RepoConfigEnableContributorsOnlyAuditEntry",
        "RepoConfigEnableSockpuppetDisallowedAuditEntry",
        "RepoConfigLockAnonymousGitAccessAuditEntry",
        "RepoConfigUnlockAnonymousGitAccessAuditEntry",
        "RepoCreateAuditEntry",
        "RepoDestroyAuditEntry",
        "RepoRemoveMemberAuditEntry",
        "RepoRemoveTopicAuditEntry",
        "Repository",
        "RepositoryCustomProperty",
        "RepositoryDependabotAlertsThread",
        "RepositoryInvitation",
        "RepositoryMigration",
        "RepositoryRule",
        "RepositoryRuleset",
        "RepositoryRulesetBypassActor",
        "RepositoryTopic",
        "RepositoryVisibilityChangeDisableAuditEntry",
        "RepositoryVisibilityChangeEnableAuditEntry",
        "RepositoryVulnerabilityAlert",
        "ReviewDismissalAllowance",
        "ReviewDismissedEvent",
        "ReviewRequest",
        "ReviewRequestRemovedEvent",
        "ReviewRequestedEvent",
        "SavedReply",
        "SecurityAdvisory",
        "SponsorsActivity",
        "SponsorsListing",
        "SponsorsListingFeaturedItem",
        "SponsorsTier",
        "Sponsorship",
        "SponsorshipNewsletter",
        "Status",
        "StatusCheckRollup",
        "StatusContext",
        "SubIssueAddedEvent",
        "SubIssueRemovedEvent",
        "SubscribedEvent",
        "Tag",
        "Team",
        "TeamAddMemberAuditEntry",
        "TeamAddRepositoryAuditEntry",
        "TeamChangeParentTeamAuditEntry",
        "TeamRemoveMemberAuditEntry",
        "TeamRemoveRepositoryAuditEntry",
        "Topic",
        "TransferredEvent",
        "Tree",
        "UnassignedEvent",
        "UnlabeledEvent",
        "UnlockedEvent",
        "UnmarkedAsDuplicateEvent",
        "UnpinnedEvent",
        "UnsubscribedEvent",
        "User",
        "UserBlockedEvent",
        "UserContentEdit",
        "UserList",
        "UserNamespaceRepository",
        "UserStatus",
        "VerifiableDomain",
        "Workflow",
        "WorkflowRun",
        "WorkflowRunFile",
    ] = Field(alias="__typename")


class FetchProjectFieldsNodeProjectV2(BaseModel):
    typename__: Literal["ProjectV2"] = Field(alias="__typename")
    fields: "FetchProjectFieldsNodeProjectV2Fields"


class FetchProjectFieldsNodeProjectV2Fields(BaseModel):
    nodes: Optional[
        list[
            Optional[
                Annotated[
                    Union[
                        "FetchProjectFieldsNodeProjectV2FieldsNodesProjectV2Field",
                        "FetchProjectFieldsNodeProjectV2FieldsNodesProjectV2IterationField",
                        "FetchProjectFieldsNodeProjectV2FieldsNodesProjectV2SingleSelectField",
                    ],
                    Field(discriminator="typename__"),
                ]
            ]
        ]
    ]


class FetchProjectFieldsNodeProjectV2FieldsNodesProjectV2Field(BaseModel):
    typename__: Literal["ProjectV2Field"] = Field(alias="__typename")
    id: str
    name: str
    data_type: ProjectV2FieldType = Field(alias="dataType")


class FetchProjectFieldsNodeProjectV2FieldsNodesProjectV2IterationField(BaseModel):
    typename__: Literal["ProjectV2IterationField"] = Field(alias="__typename")
    id: str
    name: str
    data_type: ProjectV2FieldType = Field(alias="dataType")
    configuration: (
        "FetchProjectFieldsNodeProjectV2FieldsNodesProjectV2IterationFieldConfiguration"
    )


class FetchProjectFieldsNodeProjectV2FieldsNodesProjectV2IterationFieldConfiguration(
    BaseModel
):
    iterations: list[
        "FetchProjectFieldsNodeProjectV2FieldsNodesProjectV2IterationFieldConfigurationIterations"
    ]


class FetchProjectFieldsNodeProjectV2FieldsNodesProjectV2IterationFieldConfigurationIterations(
    BaseModel
):
    id: str
    title: str
    start_date: date = Field(alias="startDate")
    duration: int


class FetchProjectFieldsNodeProjectV2FieldsNodesProjectV2SingleSelectField(BaseModel):
    typename__: Literal["ProjectV2SingleSelectField"] = Field(alias="__typename")
    id: str
    name: str
    data_type: ProjectV2FieldType = Field(alias="dataType")
    options: list[
        "FetchProjectFieldsNodeProjectV2FieldsNodesProjectV2SingleSelectFieldOptions"
    ]


class FetchProjectFieldsNodeProjectV2FieldsNodesProjectV2SingleSelectFieldOptions(
    BaseModel
):
    id: str
    name: str


FetchProjectFields.model_rebuild()
FetchProjectFieldsNodeProjectV2.model_rebuild()
FetchProjectFieldsNodeProjectV2Fields.model_rebuild()
FetchProjectFieldsNodeProjectV2FieldsNodesProjectV2IterationField.model_rebuild()
FetchProjectFieldsNodeProjectV2FieldsNodesProjectV2IterationFieldConfiguration.model_rebuild()
FetchProjectFieldsNodeProjectV2FieldsNodesProjectV2SingleSelectField.model_rebuild()
