# Generated by ariadne-codegen
# Source: src/planpilot_v2/providers/github/operations

from typing import Optional

from .base_model import BaseModel


class FetchRepo(BaseModel):
    repository: Optional["FetchRepoRepository"]


class FetchRepoRepository(BaseModel):
    id: str


FetchRepo.model_rebuild()
