# Generated by ariadne-codegen
# Source: src/planpilot_v2/providers/github/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class FetchUserProject(BaseModel):
    user: Optional["FetchUserProjectUser"]


class FetchUserProjectUser(BaseModel):
    project_v_2: Optional["FetchUserProjectUserProjectV2"] = Field(alias="projectV2")


class FetchUserProjectUserProjectV2(BaseModel):
    id: str


FetchUserProject.model_rebuild()
FetchUserProjectUser.model_rebuild()
