# Generated by ariadne-codegen
# Source: src/planpilot_v2/providers/github/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class FetchOrgProject(BaseModel):
    organization: Optional["FetchOrgProjectOrganization"]


class FetchOrgProjectOrganization(BaseModel):
    project_v_2: Optional["FetchOrgProjectOrganizationProjectV2"] = Field(
        alias="projectV2"
    )


class FetchOrgProjectOrganizationProjectV2(BaseModel):
    id: str


FetchOrgProject.model_rebuild()
FetchOrgProjectOrganization.model_rebuild()
