# Generated by ariadne-codegen
# Source: src/planpilot_v2/providers/github/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class FetchProject(BaseModel):
    organization: Optional["FetchProjectOrganization"]


class FetchProjectOrganization(BaseModel):
    project_v_2: Optional["FetchProjectOrganizationProjectV2"] = Field(alias="projectV2")


class FetchProjectOrganizationProjectV2(BaseModel):
    id: str


FetchProject.model_rebuild()
FetchProjectOrganization.model_rebuild()
