# Generated by ariadne-codegen
# Source: src/planpilot_v2/providers/github/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class FetchRepo(BaseModel):
    repository: Optional["FetchRepoRepository"]


class FetchRepoRepository(BaseModel):
    id: str
    labels: Optional["FetchRepoRepositoryLabels"]
    issue_types: Optional["FetchRepoRepositoryIssueTypes"] = Field(alias="issueTypes")


class FetchRepoRepositoryLabels(BaseModel):
    nodes: Optional[list[Optional["FetchRepoRepositoryLabelsNodes"]]]


class FetchRepoRepositoryLabelsNodes(BaseModel):
    id: str
    name: str


class FetchRepoRepositoryIssueTypes(BaseModel):
    nodes: Optional[list[Optional["FetchRepoRepositoryIssueTypesNodes"]]]


class FetchRepoRepositoryIssueTypesNodes(BaseModel):
    id: str
    name: str


FetchRepo.model_rebuild()
FetchRepoRepository.model_rebuild()
FetchRepoRepositoryLabels.model_rebuild()
FetchRepoRepositoryIssueTypes.model_rebuild()
