# Generated by ariadne-codegen
# Source: src/planpilot_v2/providers/github/operations

from typing import Optional

from .base_model import BaseModel


class IssueCore(BaseModel):
    id: str
    number: int
    url: str
    title: str
    body: str
    labels: Optional["IssueCoreLabels"]


class IssueCoreLabels(BaseModel):
    nodes: Optional[list[Optional["IssueCoreLabelsNodes"]]]


class IssueCoreLabelsNodes(BaseModel):
    id: str
    name: str


IssueCore.model_rebuild()
