# Generated by ariadne-codegen
# Source: src/planpilot_v2/providers/github/schema.graphql

from datetime import date, datetime
from typing import Annotated, Any, Optional, Union

from pydantic import Field, PlainSerializer

from .base_model import BaseModel, Upload
