# Generated by ariadne-codegen
# Source: src/planpilot_v2/providers/github/operations

__all__ = [
    "ADD_BLOCKED_BY_GQL",
    "ADD_PROJECT_ITEM_GQL",
    "ADD_SUB_ISSUE_GQL",
    "CREATE_ISSUE_GQL",
    "CREATE_LABEL_GQL",
    "FETCH_PROJECT_GQL",
    "FETCH_PROJECT_ITEMS_GQL",
    "FETCH_RELATIONS_GQL",
    "FETCH_REPO_GQL",
    "SEARCH_ISSUES_GQL",
    "UPDATE_ISSUE_GQL",
    "UPDATE_PROJECT_FIELD_GQL",
]

ADD_BLOCKED_BY_GQL = """
mutation AddBlockedBy($blockedId: ID!, $blockerId: ID!) {
  addBlockedBy(input: {issueId: $blockedId, blockingIssueId: $blockerId}) {
    issue {
      id
    }
  }
}
"""

ADD_PROJECT_ITEM_GQL = """
mutation AddProjectItem($projectId: ID!, $contentId: ID!) {
  addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
    item {
      id
    }
  }
}
"""

ADD_SUB_ISSUE_GQL = """
mutation AddSubIssue($parentId: ID!, $childId: ID!) {
  addSubIssue(input: {issueId: $parentId, subIssueId: $childId}) {
    issue {
      id
    }
  }
}
"""

CREATE_ISSUE_GQL = """
mutation CreateIssue($repositoryId: ID!, $title: String!, $body: String!) {
  createIssue(input: {repositoryId: $repositoryId, title: $title, body: $body}) {
    issue {
      id
    }
  }
}
"""

CREATE_LABEL_GQL = """
mutation CreateLabel($repositoryId: ID!, $name: String!) {
  createLabel(input: {repositoryId: $repositoryId, name: $name, color: "0366d6"}) {
    label {
      id
    }
  }
}
"""

FETCH_PROJECT_GQL = """
query FetchProject($owner: String!, $number: Int!) {
  organization(login: $owner) {
    projectV2(number: $number) {
      id
    }
  }
}
"""

FETCH_PROJECT_ITEMS_GQL = """
query FetchProjectItems($projectId: ID!, $cursor: String) {
  node(id: $projectId) {
    __typename
    ... on ProjectV2 {
      items(first: 100, after: $cursor) {
        pageInfo {
          hasNextPage
          endCursor
        }
      }
    }
  }
}
"""

FETCH_RELATIONS_GQL = """
query FetchRelations($ids: [ID!]!) {
  nodes(ids: $ids) {
    __typename
    ... on Issue {
      id
      parent {
        id
      }
      blockedBy(first: 100) {
        nodes {
          id
        }
      }
    }
  }
}
"""

FETCH_REPO_GQL = """
query FetchRepo($owner: String!, $name: String!) {
  repository(owner: $owner, name: $name) {
    id
  }
}
"""

SEARCH_ISSUES_GQL = """
query SearchIssues($query: String!, $cursor: String) {
  search(type: ISSUE, query: $query, first: 100, after: $cursor) {
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
"""

UPDATE_ISSUE_GQL = """
mutation UpdateIssue($id: ID!, $title: String, $body: String) {
  updateIssue(input: {id: $id, title: $title, body: $body}) {
    issue {
      id
    }
  }
}
"""

UPDATE_PROJECT_FIELD_GQL = """
mutation UpdateProjectField($projectId: ID!, $itemId: ID!, $fieldId: ID!, $optionId: String!) {
  updateProjectV2ItemFieldValue(
    input: {projectId: $projectId, itemId: $itemId, fieldId: $fieldId, value: {singleSelectOptionId: $optionId}}
  ) {
    projectV2Item {
      id
    }
  }
}
"""
