# Generated by ariadne-codegen
# Source: src/planpilot_v2/providers/github/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class RemoveBlockedBy(BaseModel):
    remove_blocked_by: Optional["RemoveBlockedByRemoveBlockedBy"] = Field(
        alias="removeBlockedBy"
    )


class RemoveBlockedByRemoveBlockedBy(BaseModel):
    issue: Optional["RemoveBlockedByRemoveBlockedByIssue"]


class RemoveBlockedByRemoveBlockedByIssue(BaseModel):
    id: str


RemoveBlockedBy.model_rebuild()
RemoveBlockedByRemoveBlockedBy.model_rebuild()
