# Generated by ariadne-codegen
# Source: src/planpilot_v2/providers/github/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class RemoveSubIssue(BaseModel):
    remove_sub_issue: Optional["RemoveSubIssueRemoveSubIssue"] = Field(
        alias="removeSubIssue"
    )


class RemoveSubIssueRemoveSubIssue(BaseModel):
    issue: Optional["RemoveSubIssueRemoveSubIssueIssue"]
    sub_issue: Optional["RemoveSubIssueRemoveSubIssueSubIssue"] = Field(
        alias="subIssue"
    )


class RemoveSubIssueRemoveSubIssueIssue(BaseModel):
    id: str


class RemoveSubIssueRemoveSubIssueSubIssue(BaseModel):
    id: str


RemoveSubIssue.model_rebuild()
RemoveSubIssueRemoveSubIssue.model_rebuild()
