# Generated by ariadne-codegen
# Source: src/planpilot_v2/providers/github/operations


from pydantic import Field

from .base_model import BaseModel


class SearchIssues(BaseModel):
    search: "SearchIssuesSearch"


class SearchIssuesSearch(BaseModel):
    page_info: "SearchIssuesSearchPageInfo" = Field(alias="pageInfo")


class SearchIssuesSearchPageInfo(BaseModel):
    has_next_page: bool = Field(alias="hasNextPage")
    end_cursor: str | None = Field(alias="endCursor")


SearchIssues.model_rebuild()
SearchIssuesSearch.model_rebuild()
