# Generated by ariadne-codegen
# Source: src/planpilot_v2/providers/github/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class UpdateIssue(BaseModel):
    update_issue: Optional["UpdateIssueUpdateIssue"] = Field(alias="updateIssue")


class UpdateIssueUpdateIssue(BaseModel):
    issue: Optional["UpdateIssueUpdateIssueIssue"]


class UpdateIssueUpdateIssueIssue(BaseModel):
    id: str


UpdateIssue.model_rebuild()
UpdateIssueUpdateIssue.model_rebuild()
