# Generated by ariadne-codegen
# Source: src/planpilot_v2/providers/github/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class UpdateProjectField(BaseModel):
    update_project_v_2_item_field_value: Optional[
        "UpdateProjectFieldUpdateProjectV2ItemFieldValue"
    ] = Field(alias="updateProjectV2ItemFieldValue")


class UpdateProjectFieldUpdateProjectV2ItemFieldValue(BaseModel):
    project_v_2_item: Optional[
        "UpdateProjectFieldUpdateProjectV2ItemFieldValueProjectV2Item"
    ] = Field(alias="projectV2Item")


class UpdateProjectFieldUpdateProjectV2ItemFieldValueProjectV2Item(BaseModel):
    id: str


UpdateProjectField.model_rebuild()
UpdateProjectFieldUpdateProjectV2ItemFieldValue.model_rebuild()
